monolog:
    channels: ['scraper']

    handlers:
        scraper:
            type: stream
            path: '%kernel.logs_dir%/scraper.log'
            level: debug
            channels: ['scraper']
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!scraper']
